### PR TITLE
Mcnp material formatting

### PR DESCRIPTION
**Pull request by RossWorrall**
Formatting changes to mcnp and serpent material output format for floats, to create a uniform scientific format.

### CODE REVIEW

**Comment by shimwell** [comment]
Looks great @RossWorrall feel free to merge

**Comment by shimwell** [comment]
I might be tempted to move that ```decimal_places``` varible to the class init and keep the default to 6. But this would allow users to change the setting if they like

**Comment by shimwell** [comment]
@RossWorrall I've moved the decimal places from utils.py to the class constructors so that the user can change the settings. Default is still 8. Also added a few more tests and changed the 

```f'{isotope[1]:{mat.decimal_places}e}'```

to

```f'{isotope[1]:.{mat.decimal_places}e}'```

What do you think is this how you wanted it?

Also currently the density values changing to the number of decimal places as well? Are you sure you want this to happen

**Comment by RossWorrall** [comment]
Hi @Shimwell, this looks good. The code inspector is telling you off though ;)

**Comment by shimwell** [comment]
> Hi @Shimwell, this looks good. The code inspector is telling you off though ;)

Super, I shall merge. Perhaps go back and fix the code inspector stuff later

**Pull request merged**
